version: 1
formatters:
  simple:
    format: '[%(asctime)s][%(levelname)s]%(name)s %(message)s'
handlers:
  stdout:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  MainLogger:
    level: DEBUG
    handlers: [stdout]
    propagate: no
  HeartbeatLogger:
    level: DEBUG
    handlers: [stdout]
    propagate: no
